In [1]:
import pandas as pd
import numpy as np
from collections import Counter

In [16]:
survey_df  = pd.read_csv('survey_results_public.csv')

survey_df.head()

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
0,1,I am a developer by profession,Yes,NaN,13,Monthly,NaN,NaN,Germany,European Euro,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27
1,2,I am a developer by profession,No,NaN,19,NaN,NaN,NaN,United Kingdom,Pound sterling,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,NaN,7,4
2,3,I code primarily as a hobby,Yes,NaN,15,NaN,NaN,NaN,Russian Federation,NaN,...,Neither easy nor difficult,Appropriate in length,NaN,NaN,NaN,NaN,Somewhat more welcome now than last year,NaN,4,NaN
3,4,I am a developer by profession,Yes,25.0,18,NaN,NaN,NaN,Albania,Albanian lek,...,NaN,NaN,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat less welcome now than last year,40.0,7,4
4,5,"I used to be a developer by profession, but no...",Yes,31.0,16,NaN,NaN,NaN,United States,NaN,...,Easy,Too short,No,"Computer science, computer engineering, or sof...",Django;Ruby on Rails,Ruby on Rails,Just as welcome now as I felt last year,NaN,15,8

In [17]:
survey_df.shape

(64461, 61)

In [18]:
languages = survey_df['LanguageWorkedWith'].to_frame()
languages

                                      LanguageWorkedWith
0                                 C#;HTML/CSS;JavaScript
1                                       JavaScript;Swift
2                               Objective-C;Python;Swift
3                                                    NaN
4                                      HTML/CSS;Ruby;SQL
...                                                  ...
64456                                                NaN
64457  Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...
64458                                                NaN
64459                                           HTML/CSS
64460                    C#;HTML/CSS;Java;JavaScript;SQL

[64461 rows x 1 columns]

In [19]:
def split_function(series):
    for idx,row in series[series.notna()].iterrows():

SyntaxError: unexpected EOF while parsing (<ipython-input-19-b826e2cd3978>, line 2)

In [21]:
lst = []
for idx,row in languages['LanguageWorkedWith'][languages['LanguageWorkedWith'].notna()].iteritems():
    langs = row.split(';')
#     print(idx,langs)
    for lang in langs:
        if lang not in lst:
            lst.append(lang)
            languages[lang] = False
        languages.loc[idx,lang] = True 

        
languages.head()

,LanguageWorkedWith,C#,HTML/CSS,JavaScript,Swift,Objective-C,Python,Ruby,SQL,Java,...,VBA,Perl,Scala,C++,Go,Haskell,Rust,Dart,Julia,Assembly
0,C#;HTML/CSS;JavaScript,True,True,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,JavaScript;Swift,False,False,True,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,Objective-C;Python;Swift,False,False,False,True,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,NaN,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,HTML/CSS;Ruby;SQL,False,True,False,False,False,False,True,True,False,...,False,False,False,False,False,False,False,False,False,False

In [23]:
languages.iloc[:,1:].sum()

C#                       18041
HTML/CSS                 36181
JavaScript               38822
Swift                     3397
Objective-C               2340
Python                   25287
Ruby                      4046
SQL                      31413
Java                     23074
PHP                      15007
C                        12487
TypeScript               14578
Bash/Shell/PowerShell    18980
Kotlin                    4468
R                         3288
VBA                       3499
Perl                      1796
Scala                     2052
C++                      13707
Go                        5038
Haskell                   1222
Rust                      2929
Dart                      2280
Julia                      519
Assembly                  3553
dtype: int64

In [35]:
c = set()
for i in list(languages['LanguageWorkedWith'].str.split(';')):
    try:
        for j in i:
            c.add(j)
    except:
        pass
        
c

{'Assembly',
 'Bash/Shell/PowerShell',
 'C',
 'C#',
 'C++',
 'Dart',
 'Go',
 'HTML/CSS',
 'Haskell',
 'Java',
 'JavaScript',
 'Julia',
 'Kotlin',
 'Objective-C',
 'PHP',
 'Perl',
 'Python',
 'R',
 'Ruby',
 'Rust',
 'SQL',
 'Scala',
 'Swift',
 'TypeScript',
 'VBA'}

In [77]:
for lang in c:
    try:
            print(lang)
            languages[lang] = languages['LanguageWorkedWith'].str.contains(lang, na=False)
    except:
        continue

C
SQL
Assembly
Swift
Rust
Julia
Bash/Shell/PowerShell
Haskell
Go
JavaScript
C++
HTML/CSS
Perl
R
Dart
Java
VBA
Python
Objective-C
TypeScript
Kotlin
Scala
Ruby
PHP
C#

In [78]:
languages

,LanguageWorkedWith,C,SQL,Assembly,Swift,Rust,Julia,Bash/Shell/PowerShell,Haskell,Go,...,Java,VBA,Python,Objective-C,TypeScript,Kotlin,Scala,Ruby,PHP,C#
0,C#;HTML/CSS;JavaScript,True,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,True
1,JavaScript;Swift,False,False,False,True,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
2,Objective-C;Python;Swift,True,False,False,True,False,False,False,False,False,...,False,False,True,True,False,False,False,False,False,False
3,NaN,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,HTML/CSS;Ruby;SQL,True,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64456,NaN,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
64457,Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
64458,NaN,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
64459,HTML/CSS,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
64460,C#;HTML/CSS;Java;JavaScript;SQL,True,True,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,True

In [24]:
languages.iloc[:,1:].mean()

C#                       0.279875
HTML/CSS                 0.561285
JavaScript               0.602256
Swift                    0.052699
Objective-C              0.036301
Python                   0.392284
Ruby                     0.062767
SQL                      0.487318
Java                     0.357953
PHP                      0.232807
C                        0.193714
TypeScript               0.226152
Bash/Shell/PowerShell    0.294442
Kotlin                   0.069313
R                        0.051008
VBA                      0.054281
Perl                     0.027862
Scala                    0.031833
C++                      0.212640
Go                       0.078156
Haskell                  0.018957
Rust                     0.045438
Dart                     0.035370
Julia                    0.008051
Assembly                 0.055119
dtype: float64

In [79]:
languages.mean()

C                        0.725539
SQL                      0.487318
Assembly                 0.055119
Swift                    0.052699
Rust                     0.045438
Julia                    0.008051
Bash/Shell/PowerShell    0.294442
Haskell                  0.018957
Go                       0.078156
JavaScript               0.602256
HTML/CSS                 0.561285
Perl                     0.027862
R                        0.144165
Dart                     0.035370
Java                     0.709716
VBA                      0.054281
Python                   0.392284
Objective-C              0.036301
TypeScript               0.226152
Kotlin                   0.069313
Scala                    0.031833
Ruby                     0.062767
PHP                      0.232807
C#                       0.279875
dtype: float64

In [39]:
languages['LanguageWorkedWith'].str.contains('go',na=False)

0        False
1        False
2        False
3        False
4        False
         ...
64456    False
64457    False
64458    False
64459    False
64460    False
Name: LanguageWorkedWith, Length: 64461, dtype: bool

In [43]:
languages['LanguageWorkedWith'].str.contains('Go',na=False).sum()

5038

In [49]:
languages['LanguageWorkedWith'].str.contains('C++',na=False).sum()

error: multiple repeat at position 2

In [76]:
languages['LanguageWorkedWith'][45].contains('C++')

AttributeError: 'str' object has no attribute 'contains'