In [1]:
import pandas as pd

In [5]:
survey_raw_df = pd.read_csv('/Users/alenjose/Desktop/data/stack_overflow/survey_results_public.csv')

In [7]:
survey_raw_df.head()

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,...,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Slovakia,NaN,NaN,"Secondary school (e.g. American high school, G...",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,NaN,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,62268.0
1,2,I am a student who is learning to code,"Student, full-time",Netherlands,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,...,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN
2,3,"I am not primarily a developer, but I write co...","Student, full-time",Russian Federation,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,...,18-24 years old,Man,No,Prefer not to say,Prefer not to say,None of the above,None of the above,Appropriate in length,Easy,NaN
3,4,I am a developer by profession,Employed full-time,Austria,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,NaN,NaN,...,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent,I am deaf / hard of hearing,NaN,Appropriate in length,Neither easy nor difficult,NaN
4,5,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,NaN,England,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Friend or family member,17,...,25-34 years old,Man,No,NaN,White or of European descent,None of the above,NaN,Appropriate in length,Easy,NaN

In [9]:
survey_raw_df['LanguageHaveWorkedWith']

0        C++;HTML/CSS;JavaScript;Objective-C;PHP;Swift
1                                    JavaScript;Python
2                             Assembly;C;Python;R;Rust
3                                JavaScript;TypeScript
4                       Bash/Shell;HTML/CSS;Python;SQL
                             ...
83434                               Clojure;Kotlin;SQL
83435                                              NaN
83436                               Groovy;Java;Python
83437             Bash/Shell;JavaScript;Node.js;Python
83438           Delphi;Elixir;HTML/CSS;Java;JavaScript
Name: LanguageHaveWorkedWith, Length: 83439, dtype: object

In [13]:
languages = survey_raw_df['LanguageHaveWorkedWith'].to_frame()
languages

                              LanguageHaveWorkedWith
0      C++;HTML/CSS;JavaScript;Objective-C;PHP;Swift
1                                  JavaScript;Python
2                           Assembly;C;Python;R;Rust
3                              JavaScript;TypeScript
4                     Bash/Shell;HTML/CSS;Python;SQL
...                                              ...
83434                             Clojure;Kotlin;SQL
83435                                            NaN
83436                             Groovy;Java;Python
83437           Bash/Shell;JavaScript;Node.js;Python
83438         Delphi;Elixir;HTML/CSS;Java;JavaScript

[83439 rows x 1 columns]

In [15]:
lst = []
for idx,row in languages['LanguageHaveWorkedWith'][languages['LanguageHaveWorkedWith'].notna()].iteritems():
    langs = row.split(';')

    for lang in langs:
        if lang not in lst:
            lst.append(lang)
            languages[lang] = False
        languages.loc[idx,lang] = True 

        
languages.head()

,LanguageHaveWorkedWith,C++,HTML/CSS,JavaScript,Objective-C,PHP,Swift,Python,Assembly,C,...,VBA,Groovy,Clojure,APL,LISP,F#,Elixir,Erlang,Crystal,COBOL
0,C++;HTML/CSS;JavaScript;Objective-C;PHP;Swift,True,True,True,True,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,JavaScript;Python,False,False,True,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
2,Assembly;C;Python;R;Rust,False,False,False,False,False,False,True,True,True,...,False,False,False,False,False,False,False,False,False,False
3,JavaScript;TypeScript,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,Bash/Shell;HTML/CSS;Python;SQL,False,True,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False

In [16]:
languages.iloc[:,1:]

,C++,HTML/CSS,JavaScript,Objective-C,PHP,Swift,Python,Assembly,C,R,...,VBA,Groovy,Clojure,APL,LISP,F#,Elixir,Erlang,Crystal,COBOL
0,True,True,True,True,True,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,True,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
3,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,True,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83434,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
83435,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
83436,False,False,False,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,False,False
83437,False,False,True,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
83438,False,True,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False

In [17]:
languages.iloc[:,1:].sum()

C++            20057
HTML/CSS       46259
JavaScript     53587
Objective-C     2310
PHP            18130
Swift           4204
Python         39792
Assembly        4632
C              17329
R               4185
Rust            5799
TypeScript     24909
Bash/Shell     22385
SQL            38835
C#             22984
Java           29162
Node.js        27975
PowerShell      8871
Ruby            5569
Perl            2028
Matlab          3846
Kotlin          6866
Julia           1068
Haskell         1749
Delphi          1731
Go              7879
Scala           2148
Dart            4965
VBA             3847
Groovy          2479
Clojure         1552
APL              536
LISP            1096
F#               804
Elixir          1438
Erlang           651
Crystal          466
COBOL            437
dtype: int64